### ISSUE TITLE
Error! 

### ISSUE THREAD

**Issue by N3rdY-Ash** [AbdeslemSmahi/NetflixChecker#3]
'utf-8' codec can't decode byte 0xb0 in position 6788: invalid start byte
An error occurred.. Saving progress...

plz answer.

**Comment by rishabhaanand0004** [comment]
> 'utf-8' codec can't decode byte 0xb0 in position 6788: invalid start byte
> An error occurred.. Saving progress...
> 
> plz answer.

Did you find any solution ?
